### ISSUE TITLE
用户id

### ISSUE THREAD

**Issue by soFisher** [wjllp/douyin_spider#2]
这个用户id是 字母和数字 混合的吗？现在分享出来看不到纯数字的。。怎么处理呢？

**Comment by wjllp** [comment]
用户id是纯数字的，用户id和个人主页的抖音号不是同一个，把个人主页以链接的形式分享到qq或者微信就可以从url里看到用户id了

**Comment by soFisher** [comment]
找到id啦，需要点进链接后在地址栏查看。
再问一下，现在一次能解析的url有限，所以想下载全部视频，有办法可以实现吗？

**Comment by wjllp** [comment]
已实现

**Comment by soFisher** [comment]
楼主有心了 0 0 ，不过下载量500的情况下，还是不行呀。。

Traceback (most recent call last):
  File "douyin.py", line 48, in <module>
    start(xxxxxxxxxxxx,500)
  File "douyin.py", line 18, in start
    max_cursor = download(userid,maxCount,max_cursor)
  File "douyin.py", line 38, in download
    video_url = myjson['aweme_list'][i]['video']['play_addr']['url_list'][0]
IndexError: list index out of range

**Comment by soFisher** [comment]
没有要求楼主再修改意思。。 - - 感觉这么说话非常伸手党，不好意思。。

**Comment by wjllp** [comment]
是的，部分json解析会有问题，稍后上传优化后的代码

**Comment by wjllp** [comment]
哈哈 没事的  这个我没有测试过下载量很大的时候  感谢您测出了bug
